// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zxdqjiamzphtbdkiyjuy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4ZHFqaWFtenBodGJka2l5anV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1MDgyMDksImV4cCI6MjA3NDA4NDIwOX0.M-XbMLNrTrDVwyT56Wkm-hvrzKYCL-Ms9VghI_-uv9w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});